name = "kayle-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

# Note that you will need to update this to your Account ID
account_id = "b482dc77edae0b65495f7e2fba6ceb16"

tail_consumer = [{service = kayle-rust-tail}]

[vars]
CF_ACCOUNT_ID = "b482dc77edae0b65495f7e2fba6ceb16"
CF_AI_GATEWAY = "kayle"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "eeb3ba84c17047b4b2003f70502f3911"
localConnectionString = "postgres://..."