// Generated by Wrangler on Sat Sep 07 2024 11:14:35 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	CLOUDFLARE_ACCOUNT_ID: string;
	UNKEY_API_ID: string;
	UNKEY_ROOT_API_KEY: string;
	GROQ_API_KEY: string;
	AI_MODEL: string;
	AI_API_KEY: string;
	AI_BASE_URL: string;
	EMBEDDING_MODEL: string;
	ENCRYPTION_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	HYPERDRIVE: Hyperdrive;
}
