// Generated by Wrangler on Sat Aug 24 2024 11:48:28 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	CLOUDFLARE_ACCOUNT_ID: string;
	UNKEY_API_ID: string;
	UNKEY_ROOT_API_KEY: string;
	GROQ_API_KEY: string;
	AI_API_KEY: string;
	AI_BASE_URL: string;
	HYPERDRIVE: Hyperdrive;
}
