#:schema node_modules/wrangler/config-schema.json
name = "kayle-engine"
main = "app/cf.ts"
compatibility_date = "2024-08-15"
logpush = true
account_id = "fb040c8cdde6176c04d4449b52424e65"

## Node Compatibility
node_compat = true

[placement]
mode = "smart"

## Baselime
tail_consumers = [{service = "kayle-engine-tail"}]

## Hyperdrive
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f609a275589c46db9b01b84a2c63c468"
localConnectionString = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"