/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
	accessToken: string | null;
	accountId: string;
	expiresAt: Timestamp | null;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	userId: string;
}

export interface Session {
	expiresAt: Timestamp;
	id: string;
	ipAddress: string | null;
	userAgent: string | null;
	userId: string;
}

export interface User {
	createdAt: Timestamp;
	email: string;
	emailVerified: boolean;
	id: string;
	image: string | null;
	name: string;
	updatedAt: Timestamp;
}

export interface Verification {
	expiresAt: Timestamp;
	id: string;
	identifier: string;
	value: string;
}

export interface DB {
	account: Account;
	session: Session;
	user: User;
	verification: Verification;
}
