name = "kayle-js"
compatibility_date = "2023-12-01"
main = "src/index.ts"

account_id = "b482dc77edae0b65495f7e2fba6ceb16"

node_compat = true

logpush = true

tail_consumers = [
  { service = "kayle-js-tail" }
]

[vars]
CF_ACCOUNT_ID = "b482dc77edae0b65495f7e2fba6ceb16" # Cloudflare account ID
CF_AI_GATEWAY = "kayle" # Cloudflare AI Gateway
UNKEY_API_ID = "api_Q3Er9nRPV3Hf9g52ytcMQkSgi4P"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "810e791fa12d44abaad44300c68a77fb"
localConnectionString = "postgres://postgres:password@localhost:5432/hyperdrive"